export function newProducts() {
  const products = [
    {
      id: 1,
      name: 'Bell Pepper',
      price: '€6.00',
      weight: '1kg',
      cover_photo: 'images/product-1.jpeg',
    },
    {
      id: 2,
      name: 'strawberry',
      price: '€4.50',
      weight: '1 kg',
      cover_photo: 'images/product-2.jpeg',
    },
    {
      id: 3,
      name: 'Green Beans',
      price: '€3.75',
      weight: '500 grams',
      cover_photo: 'images/product-3.jpeg',
    },
    {
      id: 4,
      name: 'Purple Cabbage',
      price: '€2.00',
      weight: '1 kg',
      cover_photo: 'images/product-4.jpeg',
    },
    {
      id: 5,
      name: 'Tomatoes',
      price: '€2.49',
      weight: '1 kg',
      cover_photo: 'images/product-5.jpeg',
    },
    {
      id: 6,
      name: 'Brocolli',
      price: '€2.50',
      weight: '500 grams',
      cover_photo: 'images/product-6.jpeg',
    },
    {
      id: 7,
      name: 'Bio Carrots',
      price: '€1.99',
      weight: '1 kg',
      cover_photo: 'images/product-7.jpeg',
    },
    {
      id: 8,
      name: 'Mixed Fruits Juice',
      price: '€10.99',
      weight: 'One Bottle',
      cover_photo: 'images/product-8.jpeg',
    },
    {
      id: 9,
      name: 'Onion',
      price: '€2.49',
      weight: '1 kg',
      cover_photo: 'images/product-9.jpeg',
    },
    {
      id: 10,
      name: 'Apple',
      price: '€5.50',
      weight: '2 kg',
      cover_photo: 'images/product-10.jpeg',
    },
    {
      id: 11,
      name: 'Garlic',
      price: '€2.70',
      weight: '1 kg',
      cover_photo: 'images/product-11.jpeg',
    },
    {
      id: 12,
      name: 'Chilli Pepper',
      price: '€3.70',
      weight: '500 grams',
      cover_photo: 'images/product-12.jpeg',
    },
    {
      id: 13,
      name: 'Watermelon',
      price: '€1.99',
      weight: '1 kg',
      cover_photo: 'images/product-13.jpeg',
    },
    {
      id: 14,
      name: 'Banana',
      price: '€2.45',
      weight: '1 kg',
      cover_photo: 'images/product-14.jpeg',
    },
    {
      id: 15,
      name: 'Raspberry',
      price: '€4.99',
      weight: '500 grams',
      cover_photo: 'images/product-15.jpeg',
    },
    {
      id: 16,
      name: 'Grape',
      price: '€2.99',
      weight: '1 kg',
      cover_photo: 'images/product-16.jpeg',
    },
  ];
  return products;
}
